services:
  portfolio:
    image: ghcr.io/thibaultand261/portfolio-v3:latest
    restart: unless-stopped
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`thandria.dev`)"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.tls.certresolver=letsencrypt"

networks:
  traefik-network:
    external: true